Repository kyma-project/opentelemetry-collector-components, pull requests merged in 2024-06, with the labels that each got.

#6 Init repo
  .gitignore
  Makefile
  Makefile.Common
  cmd/otelkymacol/Makefile
  cmd/otelkymacol/builder-config.yaml
  cmd/otelkymacol/components.go
  cmd/otelkymacol/go.mod
  cmd/otelkymacol/go.sum
  cmd/otelkymacol/main.go
  cmd/otelkymacol/main_others.go
  cmd/otelkymacol/main_windows.go
  go.mod
  go.sum
  internal/components/components.go
  internal/components/components_test.go
  internal/tools/Makefile
  internal/tools/go.mod
  internal/tools/go.sum
  internal/tools/tools.go
  receiver/dummymetricsreceiver/Makefile
  receiver/dummymetricsreceiver/config.go
  receiver/dummymetricsreceiver/docs.go
  receiver/dummymetricsreceiver/factory.go
  receiver/dummymetricsreceiver/generated_component_test.go
  receiver/dummymetricsreceiver/generated_package_test.go
  receiver/dummymetricsreceiver/go.mod
  receiver/dummymetricsreceiver/go.sum
  receiver/dummymetricsreceiver/internal/metadata/generated_status.go
  receiver/dummymetricsreceiver/metadata.yaml
  receiver/dummymetricsreceiver/metrics_receiver.go
  receiver/dummymetricsreceiver/metrics_receiver_test.go
Labels: cla: yes, size/XXL, lgtm

#10 chore: Setup CODEOWNERS
  CODEOWNERS
Labels: cla: yes, lgtm, size/M

#8 chore: Add workflows
  .github/workflows/build-and-test.yml
  cmd/otelkymacol/go.mod
  receiver/dummymetricsreceiver/config.go
Labels: cla: yes, lgtm, size/L

#9 chore: add otel-builder configuration
  otel-collector/Dockerfile
  otel-collector/README.md
  otel-collector/builder-config-PR.yaml
  otel-collector/builder-config-release.yaml
  otel-collector/envs
Labels: cla: yes, lgtm, size/L

#11 feat: add build-image workflow
  .github/workflows/build-image.yaml
Labels: cla: yes, lgtm, size/M

#12 chore: fix image builder job
  .github/workflows/build-image.yaml
Labels: cla: yes, lgtm, size/M

#14 chore: Cleanup GitHub Actions
  .github/workflows/lint-markdown-links.yml
  .github/workflows/periodic-github-checks.yaml
  .github/workflows/pr-build-image.yaml
  .github/workflows/pr-code-checks.yml
  .github/workflows/pr-docu-checks.yml
  .github/workflows/pr-github-checks.yml
  .github/workflows/pull-gitleaks.yml
  .github/workflows/tag-release.yml
  .goreleaser.yaml
  .testcoverage.yml
  Makefile
  Makefile.Common
  internal/tools/go.mod
  internal/tools/go.sum
  internal/tools/tools.go
  otel-collector/envs
Labels: cla: yes, lgtm, size/L, area/ci, kind/chore

#19 chore: Fix release tag pattern in build-config
  otel-collector/builder-config-release.yaml
Labels: cla: yes, lgtm, size/XS

#13 chore: Template and readme cleanup
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/decision-record.md
  .github/ISSUE_TEMPLATE/documentation-improvement.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/new-sig-or-wg-proposal.md
  .github/ISSUE_TEMPLATE/security-vulnerability.md
  .github/issue-template.md
  .github/pull-request-template.md
  CODEOWNERS
  README.md
  docs/README.md
  docs/contributor/README.md
  docs/user/README.md
  docs/user/_sidebar.md
  otel-collector/Dockerfile
Labels: cla: yes, lgtm, size/L, area/ci, kind/chore

#20 fix: Change tag pattern for release process
  otel-collector/builder-config-release.yaml
Labels: cla: yes, lgtm, size/XS

#21 chore: Reuse compliance
  .reuse/dep5
Labels: cla: yes, lgtm, area/ci, kind/chore, size/S

#22 fix: Generate release changelog
  .github/workflows/tag-release.yml
Labels: cla: yes, lgtm, size/M

#27 chore: Add dependabot configuration
  .github/dependabot.yml
Labels: cla: yes, lgtm, size/M

#43 chore: Group dependabot PRs
  .github/dependabot.yml
Labels: cla: yes, lgtm, size/XS

#44 chore: Add sec-scanners-config
  sec-scanners-config.yaml
Labels: cla: yes, lgtm, size/XS

#46 chore: Enable all actions for dependabot
  .github/workflows/pr-code-checks.yml
Labels: cla: yes, lgtm, size/XS

#47 chore: Update dependabot.yml
  .github/dependabot.yml
Labels: cla: yes, lgtm, size/XS

#50 chore: Simplify dependabot config
  .github/dependabot.yml
Labels: cla: yes, lgtm, size/S

#51 chore: Fix dependabot config
  .github/dependabot.yml
Labels: cla: yes, lgtm, size/XS

#54 chore: Simplify dependabot Part II
  .github/dependabot.yml
Labels: cla: yes, lgtm, size/S

#18 chore: Add release process documentation
  Makefile
  docs/contributor/releasing.md
Labels: cla: yes, lgtm, size/L

#55 fix: Unhandled errors and race conditions
  receiver/dummymetricsreceiver/config.go
  receiver/dummymetricsreceiver/config_test.go
  receiver/dummymetricsreceiver/metrics_receiver.go
  receiver/dummymetricsreceiver/testdata/config.yaml
Labels: kind/bug, cla: yes, lgtm, size/M

#23 feat: Add support for local execution
  .reuse/dep5
  README.md
  cmd/otelkymacol/builder-config.yaml
  cmd/otelkymacol/components.go
  cmd/otelkymacol/go.mod
  cmd/otelkymacol/go.sum
  go.mod
  internal/k8sconfig/Makefile
  internal/k8sconfig/config.go
  internal/k8sconfig/go.mod
  internal/k8sconfig/metadata.yaml
  otel-collector/Dockerfile
  otel-collector/builder-config-PR.yaml
  otel-collector/builder-config-release.yaml
  receiver/singletonreceivercreator/README.md
  receiver/singletonreceivercreator/config.go
  receiver/singletonreceivercreator/config_test.go
  receiver/singletonreceivercreator/factory.go
  receiver/singletonreceivercreator/factory_test.go
  receiver/singletonreceivercreator/go.mod
  receiver/singletonreceivercreator/go.sum
  receiver/singletonreceivercreator/internal/k8sconfig/config.go
  receiver/singletonreceivercreator/internal/sharedcomponent/sharedcomponent.go
  receiver/singletonreceivercreator/internal/sharedcomponent/sharedcomponent_test.go
  receiver/singletonreceivercreator/receiver.go
  receiver/singletonreceivercreator/receiver_test.go
  receiver/singletonreceivercreator/samples/collectors-with-leader.yaml
  receiver/singletonreceivercreator/testdata/config.yaml
Labels: kind/feature, cla: yes, lgtm, area/singletonreceivercreator, size/XL
