Repository kyma-project/opentelemetry-collector-components, pull requests merged in 2024-10, with the labels that each got.

#135 chore: Introduce all checks passed workflow
  .github/workflows/pr-all-checks-passed.yml
  .github/workflows/pr-build-image.yaml
  .github/workflows/pr-code-checks.yml
  .github/workflows/pr-docu-checks.yml
  .github/workflows/pr-github-checks.yml
Labels: cla: yes, area/ci, kind/chore

#136 chore: Fix label check
  .github/workflows/pr-github-checks.yml
Labels: cla: yes, area/ci, kind/chore, lgtm, size/S

#149 fix: Singleton receiver creator losing all leader (#148)
  receiver/singletonreceivercreator/factory.go
  receiver/singletonreceivercreator/leader_elector.go
  receiver/singletonreceivercreator/receiver.go
  receiver/singletonreceivercreator/samples/collectors-with-leader.yaml
  receiver/singletonreceivercreator/samples/rbac.yaml
Labels: kind/bug, cla: yes, area/singletonreceivercreator, lgtm, size/L
