Repository kyma-project/opentelemetry-collector-components, pull requests merged in 2025-02, with the labels that each got.

#244 chore: Rename fields in security config
  sec-scanners-config.yaml
Labels: cla: yes, area/release, kind/chore, size/XS, lgtm

#242 chore: Update to golang 1.23.6
  cmd/otelkymacol/go.mod
  go.mod
  internal/k8sconfig/go.mod
  internal/tools/go.mod
  otel-collector/envs
  receiver/dummyreceiver/go.mod
  receiver/kymastatsreceiver/go.mod
  receiver/singletonreceivercreator/go.mod
Labels: cla: yes, area/dependency, kind/chore, lgtm, size/S

#245 chore: Renovate for golang
  .github/dependabot.yml
  cmd/otelkymacol/go.mod
  go.mod
  internal/k8sconfig/go.mod
  internal/tools/go.mod
  otel-collector/Dockerfile
  otel-collector/README.md
  otel-collector/envs
  receiver/dummyreceiver/go.mod
  receiver/kymastatsreceiver/go.mod
  receiver/singletonreceivercreator/go.mod
  renovate.json
Labels: cla: yes, area/dependency, kind/chore, size/M, lgtm

#247 chore: Enable label and milestone automation
  .github/workflows/pr-github-checks.yml
  .github/workflows/titleprefix_to_label.json
  renovate.json
Labels: cla: yes, area/ci, kind/chore, lgtm, size/L

#257 chore: enable gha update, disable dependabot
  .github/dependabot.yml
  renovate.json
Labels: cla: yes, area/ci, kind/chore, size/M, lgtm

#265 chore: Rollback unapproved github actions tj-actions/changed-files and amannn/action-semantic-pull-request
  .github/workflows/pr-code-checks.yml
  .github/workflows/pr-github-checks.yml
  cmd/otelkymacol/go.mod
  cmd/otelkymacol/go.sum
Labels: cla: yes, kind/chore, lgtm, size/S

#271 chore: Bump x/oauth2 dependency
  cmd/otelkymacol/go.mod
  cmd/otelkymacol/go.sum
  internal/k8sconfig/go.mod
  internal/k8sconfig/go.sum
  receiver/kymastatsreceiver/go.mod
  receiver/kymastatsreceiver/go.sum
  receiver/singletonreceivercreator/go.mod
  receiver/singletonreceivercreator/go.sum
Labels: cla: yes, area/dependency, kind/chore, lgtm, size/S
