Repository kyma-project/opentelemetry-collector-components, pull requests merged in 2025-03, with the labels that each got.

#274 chore: add additional permissions for image builder
  .github/workflows/pr-build-image.yaml
  .github/workflows/tag-release.yml
Labels: area/ci, kind/chore, lgtm, size/S

#276 chore: request permissions needed for creating a release
  .github/workflows/tag-release.yml
Labels: area/ci, kind/chore, size/XS, lgtm

#282 chore: Update x-net and x-tools lib
  cmd/otelkymacol/go.mod
  cmd/otelkymacol/go.sum
  go.mod
  go.sum
  internal/k8sconfig/go.mod
  internal/k8sconfig/go.sum
  internal/tools/go.sum
  receiver/dummyreceiver/go.mod
  receiver/dummyreceiver/go.sum
  receiver/kymastatsreceiver/go.mod
  receiver/kymastatsreceiver/go.sum
  receiver/singletonreceivercreator/go.mod
  receiver/singletonreceivercreator/go.sum
Labels: area/dependency, kind/chore

#286 chore: Remove and ignore generated files of local builder setup
  .gitignore
  Makefile
  cmd/otelkymacol/components.go
  cmd/otelkymacol/go.mod
  cmd/otelkymacol/go.sum
  cmd/otelkymacol/main.go
  cmd/otelkymacol/main_others.go
  cmd/otelkymacol/main_windows.go
Labels: area/ci, kind/chore

#288 fix: Use version tag for tj-actions/changed-files
  .github/workflows/pr-code-checks.yml
Labels: kind/bug, area/ci

#290 chore: ensure PR title subject doesn't start with an uppercase character
  .github/workflows/pr-github-checks.yml
Labels: area/ci, kind/chore

#295 chore: remove GH action tj-action
  .github/workflows/pr-build-image.yaml
  .github/workflows/pr-code-checks.yml
  .github/workflows/pr-docu-checks.yml
Labels: area/ci, kind/chore

#291 feat: add service enrichment processor
  Makefile
  otel-collector/Dockerfile
  otel-collector/builder-config.yaml
  processor/serviceenrichmentprocessor/Makefile
  processor/serviceenrichmentprocessor/README.md
  processor/serviceenrichmentprocessor/docs.go
  processor/serviceenrichmentprocessor/factory.go
  processor/serviceenrichmentprocessor/factory_test.go
  processor/serviceenrichmentprocessor/generated_component_test.go
  processor/serviceenrichmentprocessor/generated_package_test.go
  processor/serviceenrichmentprocessor/go.mod
  processor/serviceenrichmentprocessor/go.sum
  processor/serviceenrichmentprocessor/internal/metadata/generated_status.go
  processor/serviceenrichmentprocessor/metadata.yaml
  processor/serviceenrichmentprocessor/service_enrichment_processor_metrics_test.go
  processor/serviceenrichmentprocessor/service_name_enrichment_processor.go
  processor/serviceenrichmentprocessor/service_name_enrichment_processor_logs_test.go
  processor/serviceenrichmentprocessor/service_name_enrichment_processor_test.go
  processor/serviceenrichmentprocessor/service_name_enrichment_processor_traces_test.go
Labels: kind/feature, area/servicenameenrichmentprocessor

#302 fix: export variable to set the config
  processor/serviceenrichmentprocessor/factory.go
  processor/serviceenrichmentprocessor/service_enrichment_processor_metrics_test.go
  processor/serviceenrichmentprocessor/service_name_enrichment_processor.go
  processor/serviceenrichmentprocessor/service_name_enrichment_processor_logs_test.go
  processor/serviceenrichmentprocessor/service_name_enrichment_processor_test.go
  processor/serviceenrichmentprocessor/service_name_enrichment_processor_traces_test.go
Labels: kind/bug, area/servicenameenrichmentprocessor
