Repository kyma-project/opentelemetry-collector-components, pull requests merged in 2025-05, with the labels that each got.

#330 chore: configure permissions for all gh actions
  .github/workflows/create-release.yaml
  .github/workflows/periodic-github-checks.yaml
  .github/workflows/pr-all-checks-passed.yml
  .github/workflows/pr-build-image.yaml
  .github/workflows/pr-code-checks.yml
  .github/workflows/pr-docu-checks.yml
  .github/workflows/pr-github-checks.yml
Labels: area/ci, kind/chore

#329 chore: migrate kymastatsreceiver to use upstream k8sleaderelector extension
  cmd/otelkymacol/builder-config.yaml
  otel-collector/builder-config.yaml
  receiver/kymastatsreceiver/README.md
  receiver/kymastatsreceiver/config.go
  receiver/kymastatsreceiver/go.mod
  receiver/kymastatsreceiver/go.sum
  receiver/kymastatsreceiver/kyma_scraper.go
  receiver/kymastatsreceiver/kyma_scraper_test.go
Labels: area/dependency, kind/chore

#335 chore: remove component singletonreceivercreator
  .testcoverage.yml
  cmd/otelkymacol/builder-config.yaml
  otel-collector/builder-config.yaml
  receiver/singletonreceivercreator/.gitignore
  receiver/singletonreceivercreator/LICENSE
  receiver/singletonreceivercreator/Makefile
  receiver/singletonreceivercreator/README.md
  receiver/singletonreceivercreator/config.go
  receiver/singletonreceivercreator/config_test.go
  receiver/singletonreceivercreator/doc.go
  receiver/singletonreceivercreator/documentation.md
  receiver/singletonreceivercreator/factory.go
  receiver/singletonreceivercreator/factory_test.go
  receiver/singletonreceivercreator/generated_component_test.go
  receiver/singletonreceivercreator/generated_package_test.go
  receiver/singletonreceivercreator/go.mod
  receiver/singletonreceivercreator/go.sum
  receiver/singletonreceivercreator/internal/metadata/generated_status.go
  receiver/singletonreceivercreator/internal/metadata/generated_telemetry.go
  receiver/singletonreceivercreator/internal/metadata/generated_telemetry_test.go
  receiver/singletonreceivercreator/internal/metadatatest/generated_telemetrytest.go
  receiver/singletonreceivercreator/internal/metadatatest/generated_telemetrytest_test.go
  receiver/singletonreceivercreator/leader_elector.go
  receiver/singletonreceivercreator/leader_elector_test.go
  receiver/singletonreceivercreator/metadata.yaml
  receiver/singletonreceivercreator/receiver.go
  receiver/singletonreceivercreator/receiver_test.go
  receiver/singletonreceivercreator/runner.go
  receiver/singletonreceivercreator/runner_test.go
  receiver/singletonreceivercreator/samples/collectors-with-leader.yaml
  receiver/singletonreceivercreator/testdata/config.yaml
Labels: area/singletonreceivercreator, kind/chore

#337 feat: support ARM architectures
  .github/workflows/create-release.yaml
  .github/workflows/pr-build-image.yaml
  otel-collector/Dockerfile
Labels: kind/feature, area/dependency
