Repository kyma-project/opentelemetry-collector-components, pull requests merged in 2025-01, with the labels that each got.

#204 chore: Widen pattern for dependabot grouping
  .github/dependabot.yml
Labels: cla: yes, area/ci, kind/chore, size/XS, lgtm

#205 chore: Group all otel changes regardless of their subdirectory
  .github/dependabot.yml
Labels: cla: yes, area/dependency, kind/chore, size/XS, lgtm

#211 chore: Try splitting dependabot PRs
  .github/dependabot.yml
Labels: cla: yes, area/ci, kind/chore, lgtm, size/S

#208 chore: Remove initial delay for all checks passed
  .github/workflows/pr-all-checks-passed.yml
Labels: cla: yes, area/ci, kind/chore, size/XS

#216 feat: Release process automation
  .github/workflows/create-release.yaml
  .github/workflows/tag-release.yml
  hack/scripts/check_artifacts_existence.sh
  hack/scripts/check_release_tag.sh
  hack/scripts/create_branch_and_tag.sh
Labels: kind/feature, cla: yes, area/release, lgtm, size/L

#215 chore: Update golang and x-net
  cmd/otelkymacol/go.mod
  go.mod
  internal/k8sconfig/go.mod
  internal/k8sconfig/go.sum
  internal/tools/go.mod
  internal/tools/go.sum
  otel-collector/envs
  receiver/dummyreceiver/go.mod
  receiver/kymastatsreceiver/go.mod
  receiver/kymastatsreceiver/go.sum
  receiver/singletonreceivercreator/go.mod
  receiver/singletonreceivercreator/go.sum
Labels: cla: yes, area/dependency, kind/chore, lgtm, size/L

#223 chore: Migrate to checkmarx
  sec-scanners-config.yaml
Labels: cla: yes, area/ci, kind/chore, size/XS, lgtm

#225 chore: Enable go mod tidy as post update in renovate
  renovate.json
Labels: cla: yes, area/ci, kind/chore, size/XS, lgtm

#227 chore: Skip digest updates for go
  renovate.json
Labels: cla: yes, area/ci, kind/chore, size/S
